language: android

branches:
  only:
    - develop

android:
  components:
    - android-23
    - build-tools-23.0.3
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

# Turn off caching to avoid any caching problems
cache: false

# Use the Travis Container-Based Infrastructure
sudo: false

install:
  # Ensure Gradle wrapper is executable, download wrapper and show version
  - chmod +x ./gradlew; ls -l gradlew; ./gradlew wrapper -v

script:
  - ./gradlew clean assembleDebug
