language: android

branches:
  only:
    - master

jdk:
  - oraclejdk8

android:
  components:
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-24.2.0

    # The SDK version used to compile your project
    - android-24

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-24

    # The system image for the emulator
    - sys-img-x86-android-24

script:
   - ./gradlew build connectedCheck

before_install:
  - chmod +x gradlew
